//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCOEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCard
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string FB_Account_Url { get; set; }
    }
}
